### ISSUE TITLE
Exception in ExportInternalPackageCheck

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#121]
See https://github.com/openhab/openhab1-addons/issues/5268.

The stack trace:
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\prj\openHAB\EclipseIDE\git\openhab1-addons\bundles\binding\org
binding.homematic\META-INF\MANIFEST.MF
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:293)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:211)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
        at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
        ... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:326)
        at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:55)
        at org.openhab.tools.analysis.checkstyle.api.AbstractStaticCheck.findLineNumber(AbstractStaticCheck.java:69)
        at org.openhab.tools.analysis.checkstyle.ExportInternalPackageCheck.processFiltered(ExportInternalPackageCheck.java:47)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:314)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:284)
        ... 32 more
```

**Comment by svilenvul** [comment]
The package name is split into two rows, and `findLineNumber()` couldn't find it ...

**Comment by svilenvul** [comment]
The openhab1-addons build is green again after these changes.
