### ISSUE TITLE
Parallel builds using static-code-analysis get stuck and fail

### ISSUE THREAD

**Issue by wborn** [openhab/static-code-analysis#200]
Whenever I do a parallel build (`mvn clean install -T 1C`) of openHAB or ESH projects with static-code-analysis these builds get stuck and then after a timeout the build fails. 

When I run the same builds using `mvn clean install -T 1C -DskipChecks=true` these builds succeed.

I've succesfully used the Maven Checkstyle, PMD, Findbugs plugins on non-OH/ESH projects without these parallel build issues. Parallel builds save a lot of time when they work. 

The stacktraces suggest that `org.openhab.tools.analysis.report.ReportUtility` is not thread safe:

```
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.openhab.tools.analysis.report.ReportUtility.generateSummaryByRules(ReportUtility.java:421)
	at org.openhab.tools.analysis.report.ReportUtility.execute(ReportUtility.java:223)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
[ERROR] TransformerException occcurred 
net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; Premature end of file.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:418)
	at net.sf.saxon.event.Sender.send(Sender.java:214)
	at net.sf.saxon.event.Sender.send(Sender.java:50)
	at net.sf.saxon.Controller.transform(Controller.java:1611)
	at org.openhab.tools.analysis.report.ReportUtility.run(ReportUtility.java:264)
	at org.openhab.tools.analysis.report.ReportUtility.generateSummaryByRules(ReportUtility.java:428)
	at org.openhab.tools.analysis.report.ReportUtility.execute(ReportUtility.java:223)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
	... 19 more
---------
org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
	at net.sf.saxon.event.Sender.send(Sender.java:214)
	at net.sf.saxon.event.Sender.send(Sender.java:50)
	at net.sf.saxon.Controller.transform(Controller.java:1611)
	at org.openhab.tools.analysis.report.ReportUtility.run(ReportUtility.java:264)
	at org.openhab.tools.analysis.report.ReportUtility.generateSummaryByRules(ReportUtility.java:428)
	at org.openhab.tools.analysis.report.ReportUtility.execute(ReportUtility.java:223)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

````
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:45 min (Wall Clock)
[INFO] Finished at: 2017-09-21T22:06:12+02:00
Timeout: sub-process interrupted[INFO] Final Memory: 156M/2026M

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:findbugs (default) on project org.openhab.binding.hdanywhere: Unable to execute mojo: Execution null of goal com.github.hazendaz.spotbugs:spotbugs-maven-plugin:3.0.6:findbugs failed: Timeout: killed the sub-process -> [Help 1]
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:findbugs (default) on project org.openhab.binding.folding: Unable to execute mojo: Execution null of goal com.github.hazendaz.spotbugs:spotbugs-maven-plugin:3.0.6:findbugs failed: Timeout: killed the sub-process -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.binding.hdanywhere
Timeout: sub-process interrupted
org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
	at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:194)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:358)
Exception in thread "main" org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
	at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:194)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:364)
Timeout: sub-process interrupted
Timeout: sub-process interrupted
Timeout: sub-process interrupted
Timeout: sub-process interrupted
Timeout: sub-process interrupted
```

**Comment by kaikreuzer** [comment]
@wborn I so far never succeeded to use parallel builds for ESH/openHAB (even without SAT) - I had the impression that Tycho couldn't really cope with it. Did you use it successfully in the past?

**Comment by wborn** [comment]
Yes I can still successfully run parallel builds when I disable SAT and tests @kaikreuzer . Some of the unit tests have not been created with parallel execution in mind.

Here are some build times on my i7-6700K with all dependencies already downloaded in my local Maven repository:

| Project | Synchronous | Parallel | Speedup (S/P) |
|----|:---:|:---:|:---:|
|smarthome| 3:10 min | 1:47 min | 1.78x |
|openhab2-addons| 57 s | 31 s | 1.84x |

Where:
* **Synchronous:** `mvn clean install -DskipChecks=true -DskipTests=true`
* **Parallel:** `mvn clean install -DskipChecks=true -DskipTests=true -T 1C`

These build times will increase when tests and SAT are working and enabled. The total gains from using parallelism would also be higher in that scenario.

I've been using parallel builds on other projects as well where it reduced build times from 1h+  to ~15 minutes. Parallel builds work even better when you give them some more memory to work with. So increase/decrease `MAVEN_OPTS="-Xmx1024m"` and see if it decreases/increases your build times. 

When SAT and unit tests allow for parallel builds, you may also want build servers to use it to reduce build times and check that parallel builds still work.

**Comment by wborn** [comment]
Here is an overview of projects where unit tests start to fail due to parallel builds:

| Project         | Often Failing       | Occasionally Failing |
|-----------------|---------------------|----------------------|             
| smarthome       | dmx.test, wemo.test | hue.test             | 
| openhab2-addons |                     | feed.test            |

These projects will probably also fail in other high load environments or where there are resource conflicts. E.g. multiple build server jobs executing related unit tests.


Below follows another overview with parallel build times after removing dmx.test and wemo.test from my local build. The build times are averages of a few succesful builds (i.e. where the occasionally failing tests don't fail).

| Project         | Synchronous  | Parallel | Speedup |
|-----------------|:------------:|:--------:|:-------:|
| smarthome       | 7:54 min     | 2:59 min | 2.65x   |
| openhab2-addons | 1:50 min     | 59s      | 1.86x   |


Now with only `-DskipChecks=true`, thus:
* **Synchronous:** `mvn clean install -DskipChecks=true`
* **Parallel:** `mvn clean install -DskipChecks=true -T 1C`

It is also noteworthy that the wemo tests (when enabled) take 3:09 min to run. I.e. 29% of a synchronous smarthome build (without SAT) is spent in the wemo tests.

Upgrading the karaf-maven-plugin to 4.0.5/4.1.0 or newer should also remove its threadsafety warning, see [KARAF-4187](https://issues.apache.org/jira/browse/KARAF-4187).

When the static-code-analysis plugin is used 4 goals are executed sequentially. But I think the tasks performed in checkstyle, pmd and findbugs could be run in parallel, followed by the report goal? That could also substantially improve build times with SAT.

**Comment by kaikreuzer** [comment]
> What do you think about trying to run the ESH build parallel (this includes looking at the failing tests of course) ?

If we manage to get that working it would be awesome, I am all for it.
In my tests in the past this always failed, but I never spent the time to look any deeper into it.

**Comment by svilenvul** [comment]
I have identified two main issues while running the goals in parallel builds:
- as @wborn already mentioned the `report` goal should be executed after the `pmd`, `checkstyle` or `findbugs` goals.  I am not sure what is the best approach here:
    - Most obvious is to bind them to different phases, but there is no `pre-verify` and `post-verify` phase. The verify phase is preceded by `post-integration-test` and followed by `install`, but none of them seems to be proper;
    - Another option is to overwrite the default lifecycle and add a `pre-verify` phase;
    - From what I wrote we can instruct Maven to always execute  `pmd`, `checkstyle` and `findbugs` before the `report` goal using [an execute annotation](http://books.sonatype.com/mvnref-book/reference/writing-plugins-sect-plugins-lifecycle.html) , but we loose a little bit of flexibility 
- the report goal creates not only merged report for the single module, but also merged reports for the whole repository. In order to achieve that it creates/merges/deletes some temporary files and this causes synchronization issues when ran in parallel. This looks actually more problematic.
