### ISSUE TITLE
NullPointerException in MarkdownCheck

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#244]
See https://github.com/openhab/openhab2-addons/pull/2012#issuecomment-358773081

Stack trace: 

```
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:checkstyle (default) on project org.openhab.binding.exec: Unable to execute mojo: An error has occurred in Checkstyle report generation. Failed during checkstyle configuration: Exception was thrown while processing /Users/kgoderis/openhab2-master/git/openhab2-addons/addons/binding/org.openhab.binding.exec/README.md: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:checkstyle (default) on project org.openhab.binding.exec: Unable to execute mojo
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:96)
	at org.openhab.tools.analysis.tools.AbstractChecker.executeCheck(AbstractChecker.java:106)
	at org.openhab.tools.analysis.tools.CheckstyleChecker.execute(CheckstyleChecker.java:123)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in Checkstyle report generation.
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:171)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:94)
	... 24 more
Caused by: org.apache.maven.reporting.MavenReportException: Failed during checkstyle configuration
	at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:488)
	at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:154)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
	... 26 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /Users/kgoderis/openhab2-master/git/openhab2-addons/addons/binding/org.openhab.binding.exec/README.md
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
	at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
	... 29 more
Caused by: java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at org.openhab.tools.analysis.checkstyle.api.AbstractStaticCheck.findLineNumber(AbstractStaticCheck.java:69)
	at org.openhab.tools.analysis.checkstyle.readme.MarkdownCheck.access$000(MarkdownCheck.java:63)
	at org.openhab.tools.analysis.checkstyle.readme.MarkdownCheck$1.findLineNumber(MarkdownCheck.java:116)
	at org.openhab.tools.analysis.checkstyle.readme.MarkdownVisitor.markDownListProcessing(MarkdownVisitor.java:216)
	at org.openhab.tools.analysis.checkstyle.readme.MarkdownVisitor.processListBlock(MarkdownVisitor.java:187)
	at org.openhab.tools.analysis.checkstyle.readme.MarkdownVisitor.visit(MarkdownVisitor.java:198)
	at org.commonmark.node.BulletList.accept(BulletList.java:9)
	at org.commonmark.node.AbstractVisitor.visitChildren(AbstractVisitor.java:132)
	at org.commonmark.node.AbstractVisitor.visit(AbstractVisitor.java:28)
	at org.commonmark.node.Document.accept(Document.java:7)
	at org.openhab.tools.analysis.checkstyle.readme.MarkdownCheck.checkReadMe(MarkdownCheck.java:126)
	at org.openhab.tools.analysis.checkstyle.readme.MarkdownCheck.processFiltered(MarkdownCheck.java:81)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
	... 32 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.binding.exec
```

**Comment by svilenvul** [comment]
Fixed with #245
