### ISSUE TITLE
How to investigate PMD processing errors

### ISSUE THREAD

**Issue by marcelrv** [openhab/static-code-analysis#378]
Is there a way I can dive into what is causing this error
```
[WARNING] There are 1 PMD processing errors:
[WARNING] /home/travis/build/openhab/openhab-addons/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java: Error while parsing /home/travis/build/openhab/openhab-addons/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java
     [java] Warnings generated: 1
```

It does not seem to give any indication to what is the issue at hand

**Comment by wborn** [comment]
Since PMD is run as a Maven plugin you can enable debug by adding the `-X` or `--debug` switch to your build:

`mvn clean install -X`

This will generate loads of logging. I usually redirect the output to a file so it's easier to analyze.

I ran it on that specific add-on, and the following output shows the culprit:

```
[WARNING] There are 1 PMD processing errors:
[WARNING] /home/wouter/git/openhab/openhab-addons/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java: Error while parsing /home/wouter/git/openhab/openhab-addons/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java
net.sourceforge.pmd.PMDException: Error while parsing /home/wouter/git/openhab/openhab-addons/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:99)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: net.sourceforge.pmd.lang.java.ast.ParseException: Encountered " "." ". "" at line 88, column 79.
Was expecting one of:
    "this" ...
    <IDENTIFIER> ...
    "@" ...
    "|" ...
    "..." ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    
	at net.sourceforge.pmd.lang.java.ast.JavaParser.generateParseException(JavaParser.java:11936)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.jj_consume_token(JavaParser.java:11820)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.VariableDeclaratorId(JavaParser.java:1402)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.FormalParameter(JavaParser.java:1813)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.FormalParameters(JavaParser.java:1726)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.MethodDeclarator(JavaParser.java:1658)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.MethodDeclaration(JavaParser.java:1603)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBodyDeclaration(JavaParser.java:1239)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBody(JavaParser.java:1194)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceDeclaration(JavaParser.java:650)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.TypeDeclaration(JavaParser.java:539)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.CompilationUnit(JavaParser.java:276)
	at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:59)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	... 9 more
```

Apparently PMD cannot handle annotations on inner classes (`WatchEvent.@Nullable`), see [MiIoDatabaseWatchService.java#L88](https://github.com/openhab/openhab-addons/blob/04d25280d2882b5f9fb76dd8ffee0131ea1a32d0/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java#L88).

It seems to be a known issue, see: https://github.com/pmd/pmd/issues/1367

I've applied a workaround for this in https://github.com/openhab/openhab-addons/pull/7244 by importing the inner class.

**Comment by wborn** [comment]
Let's close this since the workaround got merged.

**Comment by marcelrv** [comment]
Thanks @wborn for your help to the topic. Very much appreciated!
